language: python

before_install:
    - echo > "${HOME}/.bashrc"
    - virtualenv "${HOME}/virtualenv/rose"
    - echo "source \"${HOME}/virtualenv/rose/bin/activate\"" >> "${HOME}/.bashrc"
    - echo "export PYTHONPATH=\"${PWD/lib/python}\"" >> "${HOME}/.bashrc"
    - source "${HOME}/.bashrc"

install:
    - pip install sphinx
    - pip install travis-sphinx

script:
    - echo "PYTHONPATH: ${PYTHONPATH}"
    - python -c "import rose"
    - python -c "import rose.config"
    - travis-sphinx --source=doc/sphinx build

after_success:
    - travis-sphinx deploy --pullrequests
