language: python

before_install:
    - echo > "${HOME}/.bashrc"
    - virtualenv "${HOME}/virtualenv/rose"
    - echo "source \"${HOME}/virtualenv/rose/bin/activate\"" >> ~/.bashrc
    - echo "export PYTHONPATH=\"${HOME/rose/lib/python}\""
    - source "${HOME}/.bashrc"

install:
    - pip install sphinx
    - pip install travis-sphinx

script:
    - travis-sphinx --source=doc/sphinx build

after_success:
    - travis-sphinx deploy --pullrequests
