language: python

before_install:
    # Create .bashrc file.
    - echo > "${HOME}/.bashrc"
    - virtualenv "${HOME}/virtualenv/rose"
    - echo "source \"${HOME}/virtualenv/rose/bin/activate\"" >> "${HOME}/.bashrc"
    - echo "export PYTHONPATH=${PWD}/lib/python:${PYTHONPATH}" >> "${HOME}/.bashrc"
    - source "${HOME}/.bashrc"

install:
    - pip install sphinx

script:
    # Build Docs.
    - sphinx-build -aEW 'doc/sphinx' 'doc/sphinx/_build'
    - make -C 'doc/sphinx' html

after_success:
    - doc/bin/deploy
