language: python

before_install:
    - echo > "${HOME}/.bashrc"
    - virtualenv "${HOME}/virtualenv/rose"
    - echo "source \"${HOME}/virtualenv/rose/bin/activate\"" >> "${HOME}/.bashrc"
    - source "${HOME}/.bashrc"

install:
    - pip install sphinx
    - pip install travis-sphinx

script:
    - PYTHONPATH="lib/python" travis-sphinx --source=doc/sphinx --outdir=doc/sphinx/_build/html build

after_success:
    - mkdir -p target/doc
    - ln -s doc/ target/doc/build
    - travis-sphinx --pullrequests --branches master,sphinx-build-test deploy
